// Item icons. Written as fill-only grids (the outline is added when composed).
// Weapons also carry a `grip`: the pixel the hero's hand closes around, so the
// same art is drawn in the hero's hand.
//
// Keys: 1 2 3 = the item's main ramp, T U V = handle/trim ramp, anything else
// is a literal palette key.

import { compose, Grid } from './pixel.js';
import { RAMPS } from './palette.js';
import { ITEMS } from '../data.js';

const rampKeys = (main, trim) => ({
  1: main[0], 2: main[1], 3: main[2],
  T: trim[0], U: trim[1], V: trim[2],
});

const weapon = (rows, grip, handle = 'leather') => ({
  rows, grip, map: (ramp) => rampKeys(RAMPS[ramp] || RAMPS.steel, RAMPS[handle]),
});

export const ICONS = {
  sword: weapon([
    '................',
    '..............1w',
    '.............112',
    '............1123',
    '...........1123.',
    '..........1123..',
    '.........1123...',
    '........1123....',
    '...y...1123.....',
    '...yY.1123......',
    '....YY123.......',
    '.....YYY........',
    '....UV.YY.......',
    '...UV...Y.......',
    '..yV............',
    '.yY.............',
  ], [4, 12]),

  dagger: weapon([
    '................',
    '................',
    '................',
    '...........1w...',
    '..........112...',
    '.........1123...',
    '........1123....',
    '.......1123.....',
    '....y.1123......',
    '....yY123.......',
    '.....YY3........',
    '....UVYY........',
    '...UV...........',
    '..UV............',
    '..y.............',
    '................',
  ], [4, 12]),

  spear: weapon([
    '............1w..',
    '...........11w2.',
    '..........1112..',
    '...........1223.',
    '..........U.23..',
    '.........UTU....',
    '........UV......',
    '.......UV.......',
    '......UV........',
    '.....UV.........',
    '....UV..........',
    '...UV...........',
    '..UV............',
    '.UV.............',
    'UV..............',
    '................',
  ], [5, 10], 'wood'),

  axe: weapon([
    '......UV........',
    '.....UUV.11.....',
    '.....UV11w12....',
    '.....UV1ww122...',
    '.....UV11w1223..',
    '.....UV1112223..',
    '.....UV2222233..',
    '.....UV.22333...',
    '.....UV..33.....',
    '.....UV.........',
    '.....TV.........',
    '.....UV.........',
    '.....UV.........',
    '.....yY.........',
    '.....UV.........',
    '......V.........',
  ], [5, 11], 'wood'),

  mace: weapon([
    '.....w.1..w.....',
    '......1121......',
    '....w112223w....',
    '.....12222233...',
    '....112w22223...',
    '.....12222233...',
    '....w122223w....',
    '......3233......',
    '.....w.yY.w.....',
    '.......UV.......',
    '.......UV.......',
    '.......TV.......',
    '.......UV.......',
    '.......UV.......',
    '.......yY.......',
    '........Y.......',
  ], [7, 11], 'wood'),

  staff: weapon([
    '......1111......',
    '.....1ww112.....',
    '.....1w1122.....',
    '.....111223.....',
    '......2233......',
    '......yyYY......',
    '.....yY.yY......',
    '.......UV.......',
    '.......TV.......',
    '.......UV.......',
    '.......UV.......',
    '.......TV.......',
    '.......UV.......',
    '.......UV.......',
    '.......yY.......',
    '........Y.......',
  ], [7, 11], 'wood'),

  gloves: { rows: [
    '................',
    '................',
    '....11112.......',
    '...1111122......',
    '...11w11222.....',
    '...1111122223...',
    '...11111222223..',
    '...1111122.223..',
    '...111112..223..',
    '...11111222233..',
    '....1112222233..',
    '....TTTTUUUUV...',
    '....UUUUUVVVV...',
    '................',
  ] },

  gloves_spiked: { rows: [
    '.....T..T.......',
    '....TT.TT.T.....',
    '....11112TT.....',
    '...1111122......',
    '...11w11222.....',
    '...1111122223...',
    '...11111222223..',
    '...1111122.223..',
    '...111112..223..',
    '...11111222233..',
    '....1112222233..',
    '....TTTTUUUUV...',
    '....UUUUUVVVV...',
    '................',
  ] },

  boots: { rows: [
    '................',
    '....TTTTUV......',
    '....11112V......',
    '....11w123......',
    '....111123......',
    '....111223......',
    '....111223......',
    '....1112223.....',
    '....11122222....',
    '...1112222223...',
    '...11122222233..',
    '...UUUUUUUVVVV..',
    '....aaaaaaaaa...',
    '................',
  ] },

  // trinkets: literal colours
  t_clover: { rows: [
    '................',
    '.....ll..ll.....',
    '....leee.eeeE...',
    '....eeeE.eeeE...',
    '.ll..eeEEeeE.ll.',
    'leeee.eeeeE.eeeE',
    'eeeeEEeeeEEeeeeE',
    '.eeeeeEElEeeeeE.',
    '..EEEeeEEEeeEE..',
    '.leeeEEeeEEeeeE.',
    'eeeeE.eeeeE.eeeE',
    '.eEE.eeE.eeE.EE.',
    '....eeeE.eeeE...',
    '.....EE.E.EE....',
    '........E.......',
    '.........E......',
  ] },
  t_fang: { rows: [
    '.....bbbbbb.....',
    '....b......b....',
    '...Y........Y...',
    '...yY......yY...',
    '....wwwwwwww....',
    '....wwwwwwwv....',
    '.....wwwwwwv....',
    '.....wwwwwv.....',
    '......wwwwv.....',
    '......wwwv......',
    '.......wwv......',
    '.......wv.......',
    '.......pP.......',
    '.......p........',
    '.......P........',
    '................',
  ] },
  t_ring: { rows: [
    '................',
    '.......rr.......',
    '......rNrR......',
    '...E..rrRR..E...',
    '..eE.yYRRYy.Ee..',
    '...yyY....Yyy...',
    '..yY........Yy..',
    '.eyY.......Yyye.',
    '..yY........YyE.',
    '..yyY......Yyy..',
    '...yyY....YyY...',
    '..E.YyyyyyyY.e..',
    '...Ee.YYYY.eE...',
    '................',
  ] },
  t_bell: { rows: [
    '.......yy.......',
    '......y..Y......',
    '......yyYY......',
    '.....iicccC.....',
    '....iicccccC....',
    '....icccccCC....',
    '....icccccCC....',
    '...iicccccCCC...',
    '...icccccccCC...',
    '..iicccccccCCC..',
    '..icccccccccCC..',
    '.iiccccccccccCC.',
    '.CCCCCCCCCCCCjj.',
    '......ww........',
    '......wc........',
    '................',
  ] },
  t_locket: { rows: [
    '.......Y........',
    '......Y.Y.......',
    '......Y.Y.......',
    '.......Y........',
    '..yyy.....yyY...',
    '.yhyyy...yyyYY..',
    '.yhyyyy.yyyyYY..',
    '.yyyyyrrryyyYY..',
    '.yyyyrNrrryyYY..',
    '..yyyrrrrRyYY...',
    '...yyyrRRyYY....',
    '....yyyyyYY.....',
    '.....yyyYY......',
    '......yYY.......',
    '.......Y........',
    '................',
  ] },
  t_metronome: { rows: [
    '.......yy.......',
    '.......BY.......',
    '......BBbb......',
    '......BsBb......',
    '.....BBsBbb.....',
    '.....BBBsbb.....',
    '....BBBBBsbb....',
    '....BBBBByybb...',
    '...BBBBBByybb...',
    '...BBBBBBBbbb...',
    '..BBBBBBBBbbbb..',
    '..aaaaaaaaaaaa..',
    '.yYYYYYYYYYYYYY.',
    '................',
  ] },
  t_charm: { rows: [
    '...yy......yy...',
    '...y........Y...',
    '....y......Y....',
    '.....y....Y.....',
    '......yyYY......',
    '.....yyYYYY.....',
    '....yrffffRY....',
    '...yrfhfffrRY...',
    '...yrfhffffrY...',
    '...yrfffffrRY...',
    '...yRrrrrrRRY...',
    '....yRrrrRRY....',
    '.....yRRRRY.....',
    '......yYYY......',
    '.......YY.......',
    '................',
  ] },
  t_hourglass: { rows: [
    '..yyyyyyyyyyyY..',
    '..YYYYYYYYYYYY..',
    '...ibwwwwwwwc...',
    '...iyyyyyyyyc...',
    '....iyyyyyyc....',
    '.....iyyyyc.....',
    '......iyyc......',
    '.......yc.......',
    '......iycc......',
    '.....iwwyycc....',
    '....iwwwyYYcc...',
    '...iwwwyyyYYc...',
    '...iyyyyyyYYc...',
    '..yyyyyyyyyyyY..',
    '..YYYYYYYYYYYY..',
    '................',
  ] },
  t_whetstone: { rows: [
    '................',
    '................',
    '................',
    '..........ss....',
    '........sswgs...',
    '......sswwsggx..',
    '....sswwssggxxz.',
    '..sswwssgggxxz..',
    '.swwssgggxxxz...',
    '.sssggggxxzz....',
    '..sggggxxzz.....',
    '...gxxxzz.......',
    '....zzz.........',
    '................',
  ] },
  t_guard: { rows: [
    '................',
    '..sssssssssssx..',
    '..swwsssssssxx..',
    '..swCCCCCCCCxx..',
    '..swCccCCCCCxx..',
    '..sCCcyyyyCCxx..',
    '..sCCCyhyYCCxx..',
    '..sCCCyyyYCCxx..',
    '...sCCCYYCCxx...',
    '...sxCCCCCCxx...',
    '....sxCCCCxx....',
    '.....sxCCxx.....',
    '......sxxx......',
    '.......xx.......',
    '................',
  ] },
  t_band: { rows: [
    '................',
    '................',
    '.....RRrrRR.....',
    '....RrNrrrrR....',
    '...Rr.yyyy.rR...',
    '..Rr.y....Y.rR..',
    '..rr.y....Y.RR..',
    '..rr.Y....Y.RR..',
    '..Rr..YYYY..rR..',
    '...RrR....RrR...',
    '....RRrrrrRR....',
    '......RRRR......',
    '................',
  ] },
  t_heart: { rows: [
    '................',
    '...xxx...xxx....',
    '..xswsx.xsssx...',
    '.xswwssxsssssx..',
    '.xsssssssssssz..',
    '.xsssrrsrrsssz..',
    '.xsssrRrrRsssz..',
    '..xssrrrrrssz...',
    '...xsssrsssz....',
    '....xsssssz.....',
    '.....xsssz......',
    '......xsz.......',
    '.......z........',
    '................',
  ] },
  t_pendant: { rows: [
    '......Y..Y......',
    '.....Y....Y.....',
    '....Y......Y....',
    '....Y......Y....',
    '.....Y....Y.....',
    '......yyyy......',
    '.....yYllYy.....',
    '....yYleeeYy....',
    '....ylweeeEy....',
    '....yleeeeEy....',
    '....yYeeeEEy....',
    '.....yYEEEy.....',
    '......yYYy......',
    '.......yy.......',
    '................',
  ] },
  t_tooth: { rows: [
    '................',
    '...wwwwwwwwww...',
    '..wwwwwwwwwwwv..',
    '..wwwhwwwwwwvv..',
    '..wwwwwwwwwwvv..',
    '...wwwwwwwwvv...',
    '...wwwvvwwwvv...',
    '...wwwv.wwwvv...',
    '....wwv..wwv....',
    '....wwv..wwv....',
    '....wrv...wv....',
    '.....r....rv....',
    '.....R.....r....',
    '...........R....',
    '................',
  ] },
};

// Tops get their own flat-lay icons (the doll piece alone is too small).
const TOP_ICONS = {
  tunic: [
    '...7788TT889...',
    '.77778TUUV8889.',
    '777778888888899',
    '777788888888899',
    '778.788888889.99',
    '....788888889..',
    '....788888889..',
    '....UUUUUUUVV..',
    '....TTUUUUVVV..',
    '....788888889..',
    '....788888899..',
  ],
  vest: [
    '..TTTT...TTTT..',
    '..T778T.T889T..',
    '..77788T.88899.',
    '.777788T.888899',
    '.777788T.888899',
    '.777888T.888899',
    '.777888T.888899',
    '.77888UU.U88899',
    '.78888TT.T88999',
    '.7888888.888899',
    '..999999.99999.',
  ],
  plate: [
    '.TTUV.....TUUV.',
    'TTUUVV777UTUUVV',
    'TUUVV7788UVUUVV',
    '.VVV77788889VV.',
    '...7777888889..',
    '...777TU88889..',
    '...7778888889..',
    '...7778888899..',
    '...UUUUUUUVVV..',
    '....7788889....',
    '....999999.....',
  ],
  robe: [
    '...7788TT889....',
    '..77778UV88899..',
    '.777778UU888889.',
    '7777.78UU888.899',
    '77...78UU888..99',
    '.....78UU8889...',
    '....778UU88899..',
    '....778UU88899..',
    '...7778UU888999.',
    '...7788UU888899.',
    '..77788UU8888999',
    '..TTTTTUUUUUVVV.',
  ],
};

export const ICON_SIZE = 20;

// Hat and top icons reuse the paper-doll shapes, so an item looks the same in
// the bag as it does on the hero. hero.js registers them here to avoid a cycle.
export const SHAPE_ICONS = { hat: {} };

export function iconGrid(itemId) {
  const it = ITEMS[itemId];
  let rows, map;
  const main = RAMPS[it.look?.ramp || it.ramp] || RAMPS.steel;
  const trim = RAMPS[it.look?.trim || it.look?.ramp] || main;
  if (it.slot === 'hat' || it.slot === 'top') {
    rows = it.slot === 'top' ? TOP_ICONS[it.look.shape] : SHAPE_ICONS.hat[it.look.shape];
    map = { 7: main[0], 8: main[1], 9: main[2], T: trim[0], U: trim[1], V: trim[2] };
  } else {
    const ic = ICONS[it.icon];
    rows = ic.rows;
    map = ic.map ? ic.map(it.ramp) : { 1: main[0], 2: main[1], 3: main[2], T: trim[0], U: trim[1], V: trim[2] };
  }
  // centre in the icon box
  const w = Math.max(...rows.map((r) => r.length));
  const h = rows.length;
  const x = Math.floor((ICON_SIZE - w) / 2);
  const y = Math.floor((ICON_SIZE - h) / 2);
  return compose(ICON_SIZE, ICON_SIZE, [{ rows, x, y, map }]);
}

export function emptyGrid() {
  return new Grid(ICON_SIZE, ICON_SIZE);
}
