import { chromium } from 'playwright';
const [url, out, sel] = process.argv.slice(2);
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 1280, height: 900 }, deviceScaleFactor: 2 });
p.on('console', (m) => m.type() === 'error' && console.log('CONSOLE', m.text()));
p.on('pageerror', (e) => console.log('PAGEERROR', e.message));
await p.goto(url, { waitUntil: 'networkidle' });
await p.waitForTimeout(1200);
await p.screenshot({ path: out, fullPage: !sel });
await b.close();
console.log('shot', out);
