import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 1280, height: 760 }, deviceScaleFactor: 2 });
const errs = [];
p.on('pageerror', (e) => errs.push('PAGEERROR ' + e.message));
await p.goto('http://localhost:5199/?seed=wager', { waitUntil: 'load' });
await p.waitForTimeout(4500);
await p.evaluate(() => { window.__lr.run.gear = { weapon: 7, cape: 24, ring: 27, helm: 10, body: 13 }; window.__lr.challenge(0); });
await p.waitForTimeout(500);
const clickText = (t) => p.evaluate((t) => [...document.querySelectorAll('.win.open .btn')].find((b) => b.textContent.trim().toLowerCase() === t)?.click(), t);
await clickText('ask for odds');
await p.waitForTimeout(400);
console.log('odds:', await p.evaluate(() => document.querySelector('.odds')?.textContent));
await clickText('agree');
await p.waitForTimeout(600);
await p.screenshot({ path: '/tmp/regear.png' });
console.log('regear:', await p.evaluate(() => document.querySelector('.regear')?.textContent));
await p.waitForTimeout(16000);
console.log('arena open:', await p.evaluate(() => window.__lr.arena.isOpen));
await p.waitForTimeout(26000);
await p.screenshot({ path: '/tmp/wfight.png' });
const after = await p.evaluate(() => ({ mesos: window.__lr.run.mesos, w: window.__lr.run.wins, l: window.__lr.run.losses, fought: window.__lr.run.foughtToday, arena: window.__lr.arena.isOpen }));
console.log('after:', JSON.stringify(after));
console.log(errs.join('\n') || 'no page errors');
await b.close();
