// Find each monster's power multiplier (HP and damage) for every day it can be
// fought on, since biomes land on a random day each run. Writes src/mobpower.js.
// Normal and Elite are tuned against careful players' builds of that day. Easy
// is tuned against a struggling player (easy hunts only, random drops), so a
// weak run can always catch up on Easy monsters.
// node tools/tune.mjs [runs] [passes]
import fs from 'node:fs';
import { Run } from '../src/game.js';
import { MOBS, BIOMES, MOB_POWER, DAYS_IN_RUN } from '../src/data.js';
import { simulate } from '../src/sim.js';
import { mobFighter } from '../src/items.js';

const N = +(process.argv[2] || 40);
const PASSES = +(process.argv[3] || 2);
const TARGET = { easy: 0.8, normal: 0.62, elite: 0.42 };
const score = (h) => h.dps * h.ehp;
const ids = BIOMES.flatMap((b) => Object.values(b.tiers).flat());

// 1. collect builds per day from careful runs and from struggling runs
function collect(weak) {
  const builds = {}; // day -> [{ me, round }]
  for (let seed = 1; seed <= N; seed++) {
    const run = new Run(seed * 977 + (weak ? 11 : 3));
    let guard = 0;
    while (!run.over && guard++ < 40) {
      let mob;
      if (!run.isDuel) {
        (builds[run.day] = builds[run.day] || []).push({ me: run.fighter(), round: run.round });
        const me = run.fighter();
        mob = run.offers.find((id) => MOBS[id].tier === 'easy');
        if (!weak) {
          mob = run.offers[0];
          for (const id of run.offers) {
            let w = 0;
            for (let k = 0; k < 6; k++) if (simulate(me, mobFighter(id, run.round), 500 + k).winner === 0) w++;
            if (w >= 5) mob = id;
          }
        }
      }
      run.fight(mob);
      run.resolve();
      while (run.loot) {
        let best = null, bestS = -1;
        for (const inst of run.loot) {
          const s = score(run.headline(run.withItem(inst)));
          if (s > bestS) { bestS = s; best = inst; }
        }
        if (weak) best = run.loot[(seed + run.round) % run.loot.length]; // no idea what's good
        const s = score(run.headline(run.withItem(best)));
        run.takeLoot(best, s > score(run.headline()) ? 'equip' : run.bagFull() ? 'discard' : 'bag');
      }
      if (!run.over) run.next();
    }
  }
  return builds;
}

// 2. binary-search each monster's power on each day
function rate(id, day, power, sample) {
  const row = MOB_POWER[id];
  row[day - 1] = power;
  let w = 0, n = 0;
  for (const b of sample) {
    const foe = mobFighter(id, b.round);
    for (let k = 0; k < 4; k++, n++) if (simulate(b.me, foe, 700 + k).winner === 0) w++;
  }
  return n ? w / n : 0;
}

for (const id of ids) MOB_POWER[id] = MOB_POWER[id] || Array(DAYS_IN_RUN).fill(1);
for (let pass = 1; pass <= PASSES; pass++) {
  // Careful players pick hunts by these powers, so later passes see truer builds.
  const careful = collect(false);
  const weak = collect(true);
  for (const id of ids) {
    const tier = MOBS[id].tier;
    for (let day = 1; day <= DAYS_IN_RUN; day++) {
      const sample = ((tier === 'easy' ? weak : careful)[day] || []).filter((_, i) => i % 2 === 0);
      let lo = 0.1, hi = 6;
      for (let it = 0; it < 11; it++) {
        const mid = (lo + hi) / 2;
        if (rate(id, day, mid, sample) > TARGET[tier]) lo = mid; else hi = mid;
      }
      MOB_POWER[id][day - 1] = Math.round(((lo + hi) / 2) * 100) / 100;
    }
    console.error(`pass ${pass} ${tier.padEnd(6)} ${MOBS[id].name.padEnd(18)} ${MOB_POWER[id].join(' ')}`);
  }
}

const lines = ids.map((id) => `  ${id}: [${MOB_POWER[id].join(', ')}],`);
fs.writeFileSync(new URL('../src/mobpower.js', import.meta.url), `// Generated by tools/tune.mjs: each monster's power on days 1-${DAYS_IN_RUN}.
// A monster's HP and damage are multiplied by its power for the day it's
// fought on, so any biome can land on any day and still hit its tier's odds.
export const MOB_POWER = {
${lines.join('\n')}
};
`);
console.error('wrote src/mobpower.js');
